[package]
name = "async-graphql-plugin-relay-example"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2018"

[dependencies]
async-graphql-plugin-relay = { path = "../" }
async-graphql = "7"
actix-web = "4.3.1"
async-graphql-actix-web = "7"
async-trait = "0.1.68"
